package test;
import java.util.HashMap;
import java.util.Map;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
// Generated by Selenium IDE
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
public class BaiduTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.gecko.driver","D:\\BrowserDriver\\geckodriver.exe");
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void baidu() {
    driver.get("https://www.baidu.com/");
    driver.manage().window().setSize(new Dimension(1160, 713));
    driver.findElement(By.id("kw")).sendKeys("自动化测试");
    driver.findElement(By.id("kw")).sendKeys(Keys.ENTER);
    driver.findElement(By.linkText("资讯")).click();
    driver.findElement(By.linkText("图片")).click();
    driver.findElement(By.linkText("贴吧")).click();
   
  }
}
