package test;
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;
public class NewsTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	System.setProperty("webdriver.gecko.driver","D:\\BrowserDriver\\geckodriver.exe");
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void news() {
    driver.get("https://www.baidu.com/");
    driver.manage().window().setSize(new Dimension(1160, 692));
    driver.findElement(By.linkText("新闻")).click();
    driver.findElement(By.linkText("国内")).click();
    driver.findElement(By.linkText("国际")).click();
    driver.findElement(By.linkText("军事")).click();
    driver.findElement(By.linkText("财经")).click();
  }
}
